name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  ci:
    name: 'Run CI'
    strategy:
      fail-fast: false # Run the whole matrix for maximum information, no matter if we fail in one entry early
      matrix:
        os:
          - 'macOS-latest'
          - 'ubuntu-latest'
          - 'windows-latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: '3.9.1'

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
        shell: bash # Explicitly use Bash because otherwise failing Windows jobs are not erroring.

      - name: Build
        run: make install
        shell: bash # Explicitly use Bash because otherwise failing Windows jobs are not erroring.

      - name: Install testing tools
        run: |
          make install-tools-testing
          go run scripts/gitlab-ci/main.go
        shell: bash # Explicitly use Bash because otherwise failing Windows jobs are not erroring.

      - name: Lint Build
        run: make lint-build-ci
        shell: bash # Explicitly use Bash because otherwise failing Windows jobs are not erroring.

      - name: Test
        run: make test
        shell: bash # Explicitly use Bash because otherwise failing Windows jobs are not erroring.
